import React from 'react';
import './PortfolioFooter.scss';

const PortfolioFooter: React.FC = () => (
    <div className="portfolio__footer">
        <p className="portfolio__footer__description">
            Generated by eedited
            <br />
            © eedited. All rights reserved.
        </p>
    </div>
);

export default PortfolioFooter;
